# Server config
server:
  port: 8080

# App Config
spring:
  application:
    name: client-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

# Discovery client config
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:8090/eureka/}
  instance:
    instance-id: client-backend-instance-${random.uuid}

# JWT
token:
  expire-time: 1800000

# For local testing
POSTGRES_URL: jdbc:postgresql://localhost:5432/clients
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
